### PR TITLE
Full Stack HW 3

### PR DESCRIPTION
**Pull request by smah29**

### CODE REVIEW

**Review by rk-pdx — APPROVED** [review]
`01-routing.js`

**Testing:** The code ran correctly, as per the homework instructions.
**Feedback:** There is nothing that I would improve for this exercise. It was interesting to see your logic in getting the cookie string and parsing to get the individual cookies.

`02-url.js`
**Testing:** The code ran correctly, as per the homework instructions.
**Feedback:** Thorough job of extracting the cookies - I liked the checking for undefined. From my experience (I could be wrong), I believe you only need the css descriptor for `border` on the <table>. I liked your method of first getting all the required information in the `result` string variable, and then simply writing that using `res.write()`.

`03-form.js`
**Testing:** The code ran correctly, as per the homework instructions.
**Feedback:** I see that you've used the same form as from Homework 2. One small suggestion I would give is, maybe you can try moving the HTML code into a separate file and serving the HTML file since it's quite a sizable piece of code (this is a stylistic choice, ultimately). Good, efficient use of `URLSearchParams()`.

**Comment by gleason9113** [comment]
The only suggestion I would have is to, as rk-pdx also suggested, move the html into its own file and serve that instead.  Nice clean code otherwise. PR approved!

**Comment by smah29** [comment]
> The only suggestion I would have is to, as rk-pdx also suggested, move the html into its own file and serve that instead. Nice clean code otherwise. PR approved!

Served html from a separate file, Thanks for suggesting

**Comment by smah29** [comment]
> `01-routing.js`
> 
> **Testing:** The code ran correctly, as per the homework instructions. **Feedback:** There is nothing that I would improve for this exercise. It was interesting to see your logic in getting the cookie string and parsing to get the individual cookies.
> 
> `02-url.js` **Testing:** The code ran correctly, as per the homework instructions. **Feedback:** Thorough job of extracting the cookies - I liked the checking for undefined. From my experience (I could be wrong), I believe you only need the css descriptor for `border` on the
> 
> . I liked your method of first getting all the required information in the `result` string variable, and then simply writing that using `res.write()`.
> `03-form.js` **Testing:** The code ran correctly, as per the homework instructions. **Feedback:** I see that you've used the same form as from Homework 2. One small suggestion I would give is, maybe you can try moving the HTML code into a separate file and serving the HTML file since it's quite a sizable piece of code (this is a stylistic choice, ultimately). Good, efficient use of `URLSearchParams()`.

Served html from a separate file, Thanks for suggesting

**Comment by JeremyIV** [comment]
Everything looks good, nice job!

**Pull request merged**
